### ISSUE TITLE
atmega32u4

### ISSUE THREAD

**Issue by tinkerBOY-git** [insidegadgets/GBxCart-RW#12]
Will the code works for atmega32u4?

**Comment by insidegadgets** [comment]
I think it should, you will just have to change the pin mappings in the code.

**Comment by tinkerBOY-git** [comment]
The atmega32u4 only has 26 available io pins while the 8515 has 35. Looking at the schematic it looks like the 32u4 cannot do it?

**Comment by insidegadgets** [comment]
Oh I see, then yes it won't work, unless you used some shift registers for the A0-A15 pins but then you can only interface with GB/GBC carts (like the Gameboy Cart Shield project does).
