### ISSUE TITLE
Firmware update asks for password

### ISSUE THREAD

**Issue by hadess** [insidegadgets/GBxCart-RW#14]
A friend of mine gave me a GBxCart RW 1.3a to try and update under Windows. I hit a password prompt then. As the device was still on my desk when I attempted to clear it, I added [Linux support to the firmware update code](https://github.com/insidegadgets/GBxCart-RW/pull/13), and tried to run the update again, and hit the same problem.

The problem happens when it runs `tsb/tsb /dev/ttyUSB0:57600 fw gbxcart_rw_v1.3_pcb_r15.hex`. Is this a defective unit?

**Comment by hadess** [comment]
CC @hguemar

**Comment by hadess** [comment]
A full log:
```sh
$ sudo ./source/gbxcart_rw_firmware_update 
[sudo] password for hadess: 
GBxCart RW Firmware Update
##########################
Connected on COM port: /dev/ttyUSB0
Detected GBxCart RW: v1.3 PCB version
Detected Firmware: 14

Firmware R15 is available. Would you like to update? (Y/[N])
>y


About to call: tsb/gbxcart_rw_wdt_reset_v1.0 17
GBxCart RW - WDT Reset by insideGadgets
################################
Done
About to call: tsb/tsb /dev/ttyUSB0:57600 fw gbxcart_rw_v1.3_pcb_r15.hex
tsb/tsb: Symbol `ospeed' has different size in shared object, consider re-linking

Password : 
```

Is the `XXX` emergency erase something recoverable, eg. can I write the new firmware on top of that? Or will it not reset the password?

**Comment by insidegadgets** [comment]
Hi there,

There is no password needed, usually when that happens there is a communication issue or the device isn't in reset anymore. Does the GUI / Console program still work ok? 

When the WDT reset is executed you should see the LED blink, is that the case? 
If so, you could try to alter the delay inside the WDT reset program. Another way around it would be to reset the ATmega yourself with a wire - connect one from the right pad of R5 (reset) to the right pad of C11 (gnd) and you should see the LED blink. Then you just have to play around with timing of when to send the tsb flash command.

**Comment by hadess** [comment]
> There is no password needed, usually when that happens there is a communication issue or the device isn't in reset anymore. Does the GUI / Console program still work ok?

Dumped a GBA game correctly just now.

> When the WDT reset is executed you should see the LED blink, is that the case?

It does blink, yes.

> If so, you could try to alter the delay inside the WDT reset program. Another way around it would be to reset the ATmega yourself with a wire - connect one from the right pad of R5 (reset) to the right pad of C11 (gnd) and you should see the LED blink. Then you just have to play around with timing of when to send the tsb flash command.

How long is the reset supposed to last? Is it only on when the red LED is on?

I've straced `tsb` and it does 150 thousand calls to `ioctl(4, FIONREAD, [0])` after sending `@@@` to see if there's a response, which there isn't. I'd have been happy poking at `tsb` but it requires FreeBasic 1.20 which is newer than the newest FreeBasic available 1.07, so I couldn't figure out how to compile it. I wonder if it's not working because `tsb` is a 32-bit program running on a 64-bit system and that the ioctl have to go through a compat layer in the kernel.

**Comment by hadess** [comment]
I don't see how the password can be optional given the firmware update and reset protocols:
http://jtxp.org/tech/tinysafeboot_en.htm#protokolle

Am I missing something?

**Comment by hadess** [comment]
Do note that the behaviour is the same on 3 different machines, one running Windows, one running Wine under a 64-bit Linux, and the machine I'm testing this on, with native Linux utilities.

**Comment by hadess** [comment]
I also tested with different USB-C cables.

**Comment by insidegadgets** [comment]
> How long is the reset supposed to last? Is it only on when the red LED is on?

Once the led blinks, it's already out of reset. I believe it's around 500ms it stays in the tsb mode waiting for new firmware. The WDT program sends the command to reboot which GBxCart does in ~250ms so WDT program waits 300ms and then tries to send the firmware update - you might need to increase that delay a little perhaps. Otherwise you can use the wire to do the reset by hand and then quickly run the tsb to flash the new firmware.

> I don't see how the password can be optional given the firmware update and reset protocols

I am not 100% sure, but I just used the defaults with tsb and it all seemed to work fine, we've had lots of users update the firmware.

**Comment by hadess** [comment]
> When the WDT reset is executed you should see the LED blink, is that the case?
> If so, you could try to alter the delay inside the WDT reset program. Another way around it would be to reset the ATmega yourself with a wire - connect one from the right pad of R5 (reset) to the right pad of C11 (gnd) and you should see the LED blink. Then you just have to play around with timing of when to send the tsb flash command.

Is it expected that C11 is completely missing on this board? Looking at the schematics this would only cause problems when dumping a cart.

![IMG_4254](https://user-images.githubusercontent.com/769861/71643146-b5dbb900-2cb5-11ea-8aec-5bc2b78d7f4e.JPG)

**Comment by hadess** [comment]
And C1 and C2 also appear missing, same photo.

**Comment by hadess** [comment]
After wiring a switch as instructed earlier in the discussion, the supplied `tsb` binary fails in the same way. If I launch it too late, I get the password prompt, if I launch it too early, it fails to connect. I've also tested a [2016 build of the tool](https://github.com/seedrobotics/tinysafeboot/tree/master/software/tsb_loader_original) to no avail.

Trying [this C reimplementation of the tsb tool](https://github.com/rpedde/tsb-c), I get:
```sh
$ sudo ~/Projects/jhbuild/tsb-c/src/tsb -d 5 -s /dev/ttyUSB0 -b 115200 flash gbxcart_rw_v1.3_pcb_r15.hex
[INFO] main.c:513 (main): Opening serial port
[DEBUG] main.c:178 (get_serial_fd): Opening /dev/ttyUSB0 at 115200 baud
[DEBUG] main.c:195 (get_serial_fd): Opened as 3
[INFO] main.c:520 (main): Uploading hex file
<snip>
[INFO] main.c:288 (read_hex_file): Read 5678 bytes of data starting at address 0000
[DEBUG] main.c:303 (device_read): Starting device read of 16 bytes
[ERROR] main.c:385 (enter_program_mode): read devinfo: read 0 instead of 16 bytes
```

If I time it properly, I get it to read either:
```
[DEBUG] main.c:303 (device_read): Starting device read of 16 bytes
[DEBUG] main.c:323 (device_read): Read 16 bytes from device
  0000  54 d3 42                                         T.B
[ERROR] main.c:393 (enter_program_mode): Error talking to firmware
```
or:
```
[DEBUG] main.c:303 (device_read): Starting device read of 16 bytes
[DEBUG] main.c:323 (device_read): Read 16 bytes from device
  0000  ac a3 82                                         ...
[ERROR] main.c:393 (enter_program_mode): Error talking to firmware
```

Any other ideas?

**Comment by rodrigorega** [comment]
I have this issue too using "gbxcart_rw_firmware_update" binary. I am using Debian 9.

**Comment by hadess** [comment]
Are the capacitors mentioned with the photo also missing from your board?

**Comment by insidegadgets** [comment]
Hi, it's normal for all 3 capacitors to not be populated, the footprints are there just in case they were ever needed. Would either of you happen to have a Windows PC you could try the update on?

**Comment by hadess** [comment]
> Would either of you happen to have a Windows PC you could try the update on?

I already did when I opened this issue, everything is pointing at a hardware problem:
https://github.com/insidegadgets/GBxCart-RW/issues/14#issue-526887637

> A friend of mine gave me a GBxCart RW 1.3a to try and update under Windows. I hit a password prompt then.

and https://github.com/insidegadgets/GBxCart-RW/issues/14#issuecomment-557483282
> Do note that the behaviour is the same on 3 different machines, one running Windows, one running Wine under a 64-bit Linux, and the machine I'm testing this on, with native Linux utilities.

Is there a chance you wrote a non-TSB enabled firmware to those devices?

**Comment by insidegadgets** [comment]
> I already did when I opened this issue, everything is pointing at a hardware problem:

Ah sorry, my bad.

> Is there a chance you wrote a non-TSB enabled firmware to those devices?

It might be possible, but very unlikely. The way to test that would be to plug it in and if the TX/RX LED turns on straight away then the TSB bootloader isn't present. With the bootloader, it's around 0.25 to 0.5 seconds before the LED turns on.

Just to confirm, when you wired that switch and you press it, you can see the TX/RX light blink shortly afterwards? If so, can you try the Windows tsb update like this: tsb\tsb.exe com%COMPORT%:57600 fw gbxcart_rw_v1.3_pcb_r15.hex

> Opening /dev/ttyUSB0 at 115200 baud

Oh I just noticed that you are trying to connect to it at 115200, it should be 57600.

Worst case -
If you like, you can send it back to me for repair. The other option would be to purchase a cheap programmer from Ebay such as the USBasp for around $3 and update the firmware that way.

**Comment by hadess** [comment]
> It might be possible, but very unlikely. The way to test that would be to plug it in and if the TX/RX LED turns on straight away then the TSB bootloader isn't present. With the bootloader, it's around 0.25 to 0.5 seconds before the LED turns on.

It turns on at the same time as the 3.3V blue LED, then off again, shortly after I release the reset switch.

> Just to confirm, when you wired that switch and you press it, you can see the TX/RX light blink shortly afterwards?

Holding the reset switch turns off the 3.3V LED, releasing it gets the TX/RX LED and the 3.3V to turn on after a short timeout, and then the TX/RX LED turns off.

> If so, can you try the Windows tsb update like this: tsb\tsb.exe com%COMPORT%:57600 fw gbxcart_rw_v1.3_pcb_r15.hex

I'll try that. But I don't see how that's going to help when that was already the correct baud rate passed by `gbxcart_rw_firmware_update.exe`, right?

> Oh I just noticed that you are trying to connect to it at 115200, it should be 57600.

My mistake. I had tested manually with 115200 and 9600.

> Worst case -
> If you like, you can send it back to me for repair. The other option would be to purchase a cheap programmer from Ebay such as the USBasp for around $3 and update the firmware that way.

It's not mine, it's @hguemar's, but I'd advise him to send it back, and cover shipping costs, but only if you manage to update it on your system without resorting to an external programmer ;)

**Comment by insidegadgets** [comment]
> I'll try that. But I don't see how that's going to help when that was already the correct baud rate passed by gbxcart_rw_firmware_update.exe, right?

Yep though the firmware_update also does the WDT reset too which is what the switch is doing for you and it's more just to rule out any possible issues in case you were trying it running on Linux as that's only just been added. So you would just run that specific command after you let go of the switch, it might take a couple of goes.

**Comment by hadess** [comment]
Not sure whether this bears repeating, but this is the USB-C variant, not the micro-USB one.

**Comment by insidegadgets** [comment]
There is no firmware difference between the 2 variants.

**Comment by hadess** [comment]
Well, that's embarrassing and weird in equal measures. I had tested the Windows update at the beginning of September, using the latest version available to me at the time (v1.32 of the GUI updater from what I can gather), and I didn't test since.

With that out of the way, the problem might be Linux specific. Maybe something specific to the serial adapter drivers?

**Comment by hadess** [comment]
I seem to have skipped a sentence in there. The manual `tsb.exe` update on Windows 10 with the latest git version worked as expected.

**Comment by insidegadgets** [comment]
Hmm yes it's possible it might be Linux specific as the transfer speed of the console interface is pretty slow compared to when running in Windows. Perhaps Linux takes a bit more time to open up the serial port too. I'll have to setup a proper Linux machine (I normally use a VM) and test it out.

**Comment by hadess** [comment]
Is the timeout something that could be changed using `tsb`'s `T` command?
`T             Change timeout factor (8...255, approx. 0.1 up to many seconds).`
If so I could try and bump it, and try writing the firmware again.

**Comment by insidegadgets** [comment]
Yes you can, I'm using a T of 25:
com$(COM_PORT):9600 T 25

(I forgot that TSB can support different baud rates).

**Comment by hadess** [comment]
I had removed the soldered on switch yesterday, and today I just tried to raise the default timeout using Windows 8 and the reset script. Unfortunately, I couldn't get `tsb.exe` to do anything, it wouldn't print any errors or warnings, wouldn't print anything when I tried to rewrite the firmware or print out firmware info.

I think that you should definitely consider raising the default timeout to a couple of seconds, which I think would make it so much easier to upgrade if/when needed. Or have a physical button which would raise the timeout for the next run to perform admin work on it.

**Comment by insidegadgets** [comment]
We now have a user specified timeout option. Also one of our users found that TSB Advanced Loader works better than the original TSB loader so we're using that for Windows users (as it's pre-compiled).
