### ISSUE TITLE
Linux firmware update: .exe files not found

### ISSUE THREAD

**Issue by rodrigorega** [insidegadgets/GBxCart-RW#15]
I am trying to update my GBxCart RW mini. After compiling it without issue I run it and gives me this error: [1] Is it expected that this Linux binary calls .exe files?

Interface program seems to work as expected: [2]

[1]
```
GBxCart_RW/GBxCart_RW_Firmware_Update/source# ./gbxcart_rw_firmware_update 
GBxCart RW Firmware Update
##########################
Config file not found
unable to open comport : No such file or directory
unable to read portsettings : Bad file descriptor
unable to read portsettings : Bad file descriptor
unable to read portsettings : Bad file descriptor
unable to read portsettings : Bad file descriptor
unable to open comport : No such file or directory
unable to open comport : No such file or directory
unable to open comport : No such file or directory
unable to open comport : No such file or directory
unable to open comport : No such file or directory
unable to open comport : No such file or directory
unable to open comport : No such file or directory
unable to open comport : No such file or directory
unable to open comport : No such file or directory
unable to open comport : No such file or directory
unable to open comport : No such file or directory
unable to open comport : No such file or directory
Connected on COM port: 17
Detected GBxCart RW: Mini PCB version
Detected Firmware: 13

Firmware R14 is available. Would you like to update? (Y/[N])
>y


sh: 1: tsbgbxcart_rw_wdt_reset_v1.0.exe: not found
sh: 1: tsbtsb.exe: not found
```

[2]
```
GBxCart_RW/GBxCart_RW_Console_Interface_v1.27# ./gbxcart_rw_console_v1.27 
GBxCart RW v1.27 by insideGadgets
################################
Connected on COM port: 18

Please select an option:
0. Read Header
1. Read ROM
2. Backup Save (Cart to PC)
3. Restore Save (PC to Cart)
4. Erase Save from Cart
5. Specify Cart ROM/MBC
6. Specify Cart RAM
7. Custom commands
8. Other options
x. Exit
>0

--- Read Header ---
Game title: KIRBY DREAM LAND
MBC type: MBC1
ROM size: 256KByte (16 banks)
RAM size: None
Header Checksum: OK

```

**Comment by insidegadgets** [comment]
Hi there, that's odd, it shouldn't call the .exe file. Near the top of the firmware_update.c file it defines if you are on Windows or everything else. I've compiled it on Ubuntu and it appears to work ok so it may be detecting your OS as Windows for some reason. The quick fix is to change the EXE_SUFFIX to "" in the #ifdef _WIN32 part.

Could you please let me know the operating system you are using?

**Comment by rodrigorega** [comment]
I am using Debian 9.

**Comment by insidegadgets** [comment]
Very strange. I've installed the latest Debian 9 on a VM and it appears to compile and not reference the exe extension. Could there be anything with your configuration that makes part of the OS appear as Windows, perhaps some Wine related configuration or similar?

**Comment by hadess** [comment]
Did you use a git version, or the latest git version, or did you get the 1.22 release instead? The 1.22 release is a bit old, probably best to use the latest version from git instead.

**Comment by rodrigorega** [comment]
Using git sources the issue has gone, thank you @hadess.

Now I am suffering the same issue as #14. Closing this issue.
