### ISSUE TITLE
Source for GUI app?

### ISSUE THREAD

**Issue by ghost** [insidegadgets/GBxCart-RW#2]
I note there's only a binary for the GUI in source control.

Also, it might be better to use GitHub Releases for the applications to keep source control "clean".

**Comment by insidegadgets** [comment]
The GUI source is quite messy at the moment, I'll need to clean it up and then it can be released.

Yes I should really use Github properly! So used to keep versions of everything myself. The biggest problem right now is how to keep the GUI, Console, MCU files, schematic all versioned properly, one may change while the others remain the same, maybe Github would be the answer to all of it.

**Comment by ghost** [comment]
Yep, I'd just do separate repositories for each

**Comment by insidegadgets** [comment]
GUI source has now been added to \GBxCart-RW\Interface_Programs\Source
