### ISSUE TITLE
White screen when booting flashed ROM on supported cartridge

### ISSUE THREAD

**Issue by zlotny** [insidegadgets/GBxCart-RW#21]
**Board**: GBxCart RW v1.3b Pro
**Firmware**: Tested R22 (stock) and R24 (updated)
**Cartridge**: Aliexpress bought M29W128GH
**Game**: Pokémon Emerald (ESP)

Hi there. I've got a few cartridges with **M29W128GH** flash that I wanted to flash. I updated my firmware to **R24** and I used (In Windows, via VM) the console flasher with option **36** (which includes **M29W128**). 

I assume that is the correct type to flash. And indeed it flashes correctly. However when I put the cartridge on my GBA SP it boots the GBA logo with the nintendo logo below, then fades to a white screen permanently.

The cartridge was working with the same rom on USA version before. I just wanted the spanish rom in it.

I tried to backup the rom from the catridge and the rom is read correctly and works in VBA, so it appears to be correctly flashed.

To rule out the ROM being wrong I made a backup of my Pokemon RUBY (the most similar ROM I have) and flashed that onto my M29W128GH. Still, no luck. White screen.

What could be the problem? Any ideas?

Pics (sorry about the bad quality. Broken stabilizer):
![image](https://user-images.githubusercontent.com/6155245/103538017-bfce6400-4e95-11eb-98eb-98ceef057210.png)
![image](https://user-images.githubusercontent.com/6155245/103538041-c52bae80-4e95-11eb-865a-1d45be28ce4f.png)

**Comment by insidegadgets** [comment]
Hi there, it's best to read the rom back and compare against the original with a hex editor. 

But I believe the issue if you try to flash Pokemon games is that they check for the flash save chip and if it doesn't respond, then it white screens / doesn't boot. You will need to use gbata to patch the game to use SRAM and install a battery. 

Please check FlashCartDB for more information: https://flashcartdb.com/index.php/Clone_and_Repo_Cart_Problems#Problems_with_GB.2FGBA_carts_without_a_battery_pre-installed
https://flashcartdb.com/index.php/How_to_Patch_GBA_Games_with_GBATA

**Comment by zlotny** [comment]
Thank you! The Pokémon issue indeed solved the issue. Honestly that was a bad issue by my side, I figured out searching by the GBA Tool suggestion you gave me and Indeed those games suffer from that boot condition.

So the patched rom totally works. Obviously it does not save but I'll will be installing a battery to fix that.

Thank you so much again, for the board, the documentation, the software and the fast-answering issue tracking ;)
