### ISSUE TITLE
Driver install hash fail

### ISSUE THREAD

**Issue by eruerable** [insidegadgets/GBxCart-RW#22]
Attempting to install the driver from the \GBxCart_RW_GUI_Interface_v1.41 directory is failing.

`Windows found drivers for your device but encountered an error while attempting to install them.

   USB-SERIAL CH340
The hash for the file is not present in the specified catalog file. The file is likely corrupt or the victim of tampering.

If you know the manufacturer of your device, you can visit their website and check the support section for drivers`

Windows 10 64-bit
GBxCart RW v1.3b Pro

I have tried redownloading the repository and re-extracting the relevant folder, but I'm not really tech savvy so couldn't think of anything else to do.

**Comment by insidegadgets** [comment]
Hi there, would you be able to see if Windows can automatically search for a driver for you?

In device manage, select the device and then select "Search automatically for updated driver software"

**Comment by eruerable** [comment]
That didn’t find anything either, I did manage to get the driver installed by disabling the driver signing requirement in windows as a workaround. Seems to be working perfectly now.
