### ISSUE TITLE
Source outdated

### ISSUE THREAD

**Issue by ibrokemypie** [insidegadgets/GBxCart-RW#6]
The latest files downloaded from https://shop.insidegadgets.com/wp-content/uploads/2018/05/GBxCart_RW_v1.25.zip provide GBxCart_RW_Console_Interface_v1.18 whereas only GBxCart_RW_Console_Interface_v1.15 is in the repo

**Comment by ibrokemypie** [comment]
This is important because my pull request actually still doesnt work when building the program from this repo, but works if you apply the same changes to 1.18

**Comment by insidegadgets** [comment]
Thanks, the source has now been updated.
