### ISSUE TITLE
Additional boards

### ISSUE THREAD

**Issue by Necrosaro420** [insidegadgets/GBxCart-RW#7]
Heya, I don't see a way to send a message, so I am hoping you see it here.  I have some PCB scans of 4 GBA games.  Maybe you can add support for them?  I know 2 will erase/write, but 2 others won't (The Mother 3 and Fire Emblem boards there) [https://ibb.co/nnzVqA](url)  Thanks!

**Comment by Necrosaro420** [comment]
![gbacarts](https://user-images.githubusercontent.com/36713801/50659152-aeca7f80-0f69-11e9-8153-6ecccb223622.jpg)

**Comment by insidegadgets** [comment]
Hi there, would you be able to provide the chip numbers on the 2 flash carts that don't work and also a link to where you purchased them from? Thanks

**Comment by Necrosaro420** [comment]
Sounds good, ill get them over to ya soon.  Will be hard to figure out where they came from specifically.  I do know they were off either alibaba or aliexpress.  Ill see if I can track down those links for ya.

**Comment by PandaUnit-TWL** [comment]
Could you take a look at this one too? I found a GBA that doesn't work, it's a recently bought copy. 

![d6bc4ca465a0f733202126f352cc46d17cd92513-1](https://user-images.githubusercontent.com/48398521/55362239-67d82180-54a7-11e9-804b-04c9d228d071.jpg)

![59c2a6244225425785869e616607753ca3b6ff33-1](https://user-images.githubusercontent.com/48398521/55362549-4deb0e80-54a8-11e9-86f3-bbc078877073.jpg)

A s29gl128n10tfi01 chip [datasheet](https://www.datasheets.com/en/datasheet/s29gl128n10tfi01-cypress-semiconductor-34778028).

[Bought](https://www.ebay.com/itm/Games-Card-Carts-For-Pokemon-GBC-GBA-GameBoy-Collection-Kids-Adults-Gifts/323216313572?ssPageName=STRK%3AMEBIDX%3AIT&var=512735130171&_trksid=p2057872.m2749.l2649) on eBay.

**Comment by Necrosaro420** [comment]
Sorry totally forgot about this, I will get them to ya soon.

**Comment by insidegadgets** [comment]
I've ordered the s29gl128n board. 

Have you tried flashing it with all the GBA cart options? If so, what happens?

Could you try this flash id query program and let me know the output - https://shop.insidegadgets.com/wp-content/uploads/2019/04/gbxcart_rw_flasher_v1.16_flash_id_check.zip

The output will look like this, we are just checking to see if the flash id command returns anything different from the read rom result:
![flashid](https://user-images.githubusercontent.com/9656315/55782288-47374980-5aef-11e9-8f5a-b757f7730cd0.JPG)

**Comment by PandaUnit-TWL** [comment]
Here you go:
![Capture](https://user-images.githubusercontent.com/48398521/55855903-c56b0e80-5b36-11e9-86e4-75b6e12adabd.PNG)

I went ahead and tried all three 32 MByte IC settings. None of them worked, all stalled before even getting started.

MSP55LV128/M got started but both stalled part way through.
29GL128EHMC also got started but stalled part way through.
Nothing else worked.





If you could look at [this ](https://www.aliexpress.com/item/Mother-3-32-Bit-Video-Game-Cartridge-Console-Card-EU-Version/32889904039.html?spm=a2g0s.9042311.0.0.78fe4c4d5GHLDU)one too. It seems like it may have the same chip as one of Necros cards. 

![20190410_022858](https://user-images.githubusercontent.com/48398521/55856536-a1103180-5b38-11e9-8882-986103e9ecc8.jpg)

![Capture](https://user-images.githubusercontent.com/48398521/55856856-94d8a400-5b39-11e9-9602-3e1575ccb46b.PNG)

M36L0R706/(2) both just barely got started, and then stalled.
All other settings stalled before even getting started.

Is there any thing else I can try to help out?

**Comment by insidegadgets** [comment]
Unfortunately that Intel based flash cart doesn't seem to work for me, I can only get as far as erasing sectors. Writing seems to return a ok response but nothing is actually written.

I've included more debug information, lets see where it stops - https://www.insidegadgets.com/wp-content/uploads/2019/04/GBxCart_RW_Console_Flasher_v1.16_s29gl128.zip

**Comment by PandaUnit-TWL** [comment]
The .exe cmd window from the "GBxCart_RW_Console_Flasher_v1.16_s29gl128" zip does not stay open and immediately closes. The regular cmd flasher and the flash ID exe you sent work fine, cmd stays open. GBxCart is plugged in, with and without cart.

Anything I should be doing to keep the cmd window open?

**Comment by insidegadgets** [comment]
Oh sorry, could you drag and drop your rom file to it.

**Comment by PandaUnit-TWL** [comment]
It finishes doing what its doing after 10 min and closes. The game has nothing playable on it when used.

**Comment by insidegadgets** [comment]
If you read back the rom, does it contain any data that was written? You can compare the files by using a hex editor like HxD.

Received the Pokemon Emerald cart, as the listing ended I tried to find a similar one but unfortunately it was a M29W128 chip.

**Comment by insidegadgets** [comment]
For the 4455LLBQO chip, one user reported it working using: https://shop.insidegadgets.com/wp-content/uploads/2019/04/GBxCart_RW_Console_Flasher_v1.16_256L30B_v8.zip

For the S29GL128 chip, could you re-run the flashing program but can you stop it before it reaches address 0x10000, then power cycle and read the header to see if the game title changed? Could just be that the erase sector covers more than 0x10000.

**Comment by PandaUnit-TWL** [comment]
That file you sent works for my mother GBA game cartridge. 

As for the Pokemon game, I stopped the flash and the game title changed to my roms name.

I also used HxD to compare the file against the read back from after a full flash attempt. They are very different. Not the same at all,

**Comment by insidegadgets** [comment]
Another user has reported that option 21 on the console flash worked for the S29GL128 cart. How large of a rom file were you flashing to it? Maybe try a 4 or 8MB rom file.

**Comment by PandaUnit-TWL** [comment]
Option 21 from the console flasher stalls somewhere between 2 and 7 hashtags with my 4 meg game. Namco Museum.gba

![image](https://user-images.githubusercontent.com/48398521/56853073-f302d680-68f0-11e9-86c1-7ac3b2ee7698.png)

The Console_Flasher_v1.16_s29gl128.zip file is the one that didn't work, but looked like it did.

**Comment by insidegadgets** [comment]
Could you please try option 21 again with the latest console flasher v1.17

**Comment by PandaUnit-TWL** [comment]
That worked.

**Comment by Liriel-666** [comment]
i have 2 Cards to submit

Nr 1 from Zelda ALTTP + 4 Swords
![IMG_20190824_190002](https://user-images.githubusercontent.com/10562572/63640607-613e8680-c6a2-11e9-97f0-e5f9aea18deb.jpg)
![IMG_20190824_182840](https://user-images.githubusercontent.com/10562572/63640611-6a2f5800-c6a2-11e9-938e-24966f4f4145.jpg)

the Little Chip has that on it:
M29W640
ST (Logo) GB6AZA6
99A9C  VS
MYS 99 205

i test all Board Settings but nothing work.
I found in https://flashcartdb.com/index.php/Main_Page the boardname BX2006 TSOPBGA 0106
but nothing to it in the Flasher or Interface.

The Other is this
![IMG_20190824_190033](https://user-images.githubusercontent.com/10562572/63640688-90092c80-c6a3-11e9-940d-d915874e3283.jpg)
![IMG_20190824_190039](https://user-images.githubusercontent.com/10562572/63640691-98616780-c6a3-11e9-850b-bfeca1d1eb6a.jpg)
![IMG_20190824_190054](https://user-images.githubusercontent.com/10562572/63640698-aca56480-c6a3-11e9-84a9-82c121e48cc0.jpg)

I see a Spansion S29GL128N10TFI01 on it but i can only write on it with the MSP55LV128M setting.
But nothing can be Save.
I but a full Battery on the 2 Pin but nothing in Sram Saves.

 I hope there can be help

**Comment by Liriel-666** [comment]
the first has

GBxCart RW Flasher v1.16 by insideGadgets
########################################
Connected on COM port: 14

          Read ROM: 0x2E, 0x0, 0x0, 0xEA, 0x24, 0xFF, 0xAE, 0x51,
Flash ID (AAA, A9): 0x20, 0x0, 0x7D, 0x22, 0x0, 0x0, 0x8, 0x0,
Flash ID (AAA, AA): 0x2E, 0x0, 0x0, 0xEA, 0x24, 0xFF, 0xAE, 0x51,
Flash ID (555, A9): 0x2E, 0x0, 0x0, 0xEA, 0x24, 0xFF, 0xAE, 0x51,
Flash ID (555, AA): 0x2E, 0x0, 0x0, 0xEA, 0x24, 0xFF, 0xAE, 0x51,
Finished

the Second show that
GBxCart RW Flasher v1.16 by insideGadgets
########################################
Connected on COM port: 14

          Read ROM: 0x0, 0x0, 0xBF, 0xB, 0xEB, 0x0, 0x0, 0x0,
Flash ID (AAA, A9): 0x2, 0x0, 0x10, 0x10, 0x55, 0x4, 0xC0, 0x0,
Flash ID (AAA, AA): 0x2E, 0x0, 0xD7, 0x1F, 0x0, 0x1F, 0x43, 0x14,
Flash ID (555, A9): 0x2E, 0x0, 0xD7, 0x1F, 0x0, 0x1F, 0x43, 0x14,
Flash ID (555, AA): 0x2E, 0x0, 0xD7, 0x1F, 0x0, 0x1F, 0x43, 0x14,
Finished

I knew that the second is minimum a 16MB Card because i install Mother 3 on it

**Comment by insidegadgets** [comment]
Hi there,

You should jump on our discord server: http://discord.gg/X2wS8eh

For the first cart, does the existing game get erased?
For the second cart, have you tried to restore 64KB of a save file, then read it back and compare the two?

If you have trouble saving: Most clone carts only come with SRAM, sometimes without a battery. If your game saves to an EEPROM or Flash then it won’t work on unless you patch it to use SRAM, the GBATA program seems to work well for this as reported by some users. If the cart you have doesn’t have a spot for a battery, then you will need to patch that game to save back to the flash. Check what save type your game uses here - https://raw.githubusercontent.com/mamedev/mame/master/hash/gba.xml

**Comment by Liriel-666** [comment]
Hi 

to the First.
I think that the rom is ereased but i think not full.
Because the nintendo tag comes on booting and then white Screen.
I test 3 of this boards

i try everything with the second card.
Games with sram save.
Games with sram save after patch through Gbata.
Rom with Flash save
Rom with eeprom save.

All with Battery installed because these 2 points are for the battery.

save the save and restore it doesnt work.

I give up that board.
I use it now for games without save function like r-typ 3
