### ISSUE TITLE
Proper code license

### ISSUE THREAD

**Issue by lpla** [insidegadgets/GBxCart-RW#8]
I read that this code is under CC-BY, but it is not encouraged for code:

https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software

(link found here - https://opensource.stackexchange.com/questions/1717/why-is-cc-by-sa-discouraged-for-code)

Maybe a MIT or Apache license fits, and has no problem with code, binaries, pictures, documents and patents.

**Comment by insidegadgets** [comment]
I've taken a look and I think I might go GPL - I like the "I open sourced my code so you should too".
